const actionsTypesAuthors = {
  INIT_AUTHORS_START: 'INIT_AUTHORS_START',
  INIT_AUTHORS_SUCCESS: 'INIT_AUTHORS_SUCCESS',
  INIT_AUTHORS_ERROR: 'INIT_AUTHORS_ERROR',

  DELETE_AUTHOR_START: 'DELETE_AUTHOR_START',
  CREATE_AUTHOR_START: 'CREATE_AUTHOR_START',
  EDIT_AUTHOR_START: 'EDIT_AUTHOR_START',
}

export default actionsTypesAuthors;
