const actionTypesBooks = {
  INIT_BOOKS_START: 'INIT_BOOKS_START',
  INIT_BOOKS_SUCCESS: 'INIT_BOOKS_SUCCESS',
  INIT_BOOKS_ERROR: 'INIT_BOOKS_ERROR',

  DELETE_BOOK_START: 'DELETE_BOOK_START',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
  DELETE_BOOK_ERROR: 'DELETE_BOOK_ERROR',
}

export default actionTypesBooks;
